const fs = require("fs");
const path = require("path");
const { ethers, artifacts } = require("hardhat");

async function main() {
  const Factory = await ethers.getContractFactory("FoodTraceability");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  const network = await ethers.provider.getNetwork();
  const artifact = await artifacts.readArtifact("FoodTraceability");
  const output = `// Generated by scripts/deploy.js\nexport const DEPLOYED_ADDRESS = "${address}";\nexport const DEPLOYED_CHAIN_ID = ${network.chainId}n;\n`;
  const abiOutput = `// Generated from the Hardhat artifact\nexport const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`;

  fs.mkdirSync(path.join(__dirname, "..", "frontend", "js"), { recursive: true });
  fs.writeFileSync(path.join(__dirname, "..", "frontend", "js", "deployment.js"), output);
  fs.writeFileSync(path.join(__dirname, "..", "frontend", "js", "abi.js"), abiOutput);

  const envPath = path.join(__dirname, "..", ".env");
  const currentEnv = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";
  const contractLine = `CONTRACT_ADDRESS=${address}`;
  const updatedEnv = /^CONTRACT_ADDRESS=.*$/m.test(currentEnv)
    ? currentEnv.replace(/^CONTRACT_ADDRESS=.*$/m, contractLine)
    : `${currentEnv.trimEnd()}${currentEnv ? "\n" : ""}${contractLine}\n`;
  fs.writeFileSync(envPath, updatedEnv);

  console.log(`FoodTraceability deployed to: ${address}`);
  console.log("Frontend address, ABI and .env were updated automatically.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
